### ISSUE TITLE
Iterating through larger data use too much memory and performance is low

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-db#134]
### Expected behavior
With the large data, it should still iterate through the small memory size with high performance

### Actual behavior
Looping through the v3 blocks for testnet data takes 30s with 5GB memory usage

### Steps to reproduce
```
(async () => {
	const db = new Database(dbPath)
	const DB_KEY_BLOCKS_ID = 'blocks:id';
	console.time('performance');

	const blocksStream = db.createReadStream({
		gte: Buffer.from(`${DB_KEY_BLOCKS_ID}:${Buffer.alloc(32, 0).toString('binary')}`),
		lte: Buffer.from(`${DB_KEY_BLOCKS_ID}:${Buffer.alloc(32, 255).toString('binary')}`),
	});

	await new Promise((resolve, reject) => {
		blocksStream
			.on('data', ({ value }) => {
			})
			.on('error', error => {
				reject(error);
			})
			.on('end', () => {
				resolve();
			});
	});
	console.timeEnd('performance');
	db.close()
})()
```

### Which version(s) does this affect? (Environment, OS, etc...)
0.3.8

**Comment by matjazv** [comment]
After consideration of different options/optimizations regarding `pub fn js_iterate(mut ctx: FunctionContext) -> JsResult<JsUndefined>` function to make it less memory intensive, we decide to leave it as it is.

Current [Neon](https://github.com/neon-bindings/neon) implementation has some limitations on how you can pass borrowed objects back to JS and this was one of the main issues, why memory optimization was not done.

We also investigated how [napi-rs](https://github.com/napi-rs/napi-rs) library works with `lisk-db` and measurements showed that a peak of a memory consumption was decreased by about 50%.
We decided to not proceed and use this library instead of `neon` because an effort in comparison to what we will be gaining would be too big.
High memory consumption only concerns `lisk-migrator` because it iterates over a large number of database elements. Lisk nodes are not affected by this because iterations are much smaller in comparison with `lisk-migrator`.
